### ISSUE TITLE
Change routing of "Sign In" link in Nav Bar

### ISSUE THREAD

**Issue by agstephens** [cedadev/fawkes-phoenix#1]
To simplify the login process:
 - Remove the extra stage (i.e. the login page) by pointing the "Sign In" link in the NavBar directory to:
 https://name-staging.ceda.ac.uk/account/auth/ceda_oauth

**Comment by tommygod3** [comment]
This has been fixed awaiting merge request from my local fork.
Logging in as admin will require manually going to `/account/login`.
