### ISSUE TITLE
Rename processes

### ISSUE THREAD

**Issue by agstephens** [cedadev/fawkes-phoenix#11]
Give the processes more meaningful names so that the user can know what she is selecting. Remove version from name. 

Also expand the Abstract for each process to elaborate on the name.

Please send suggested new names and abstracts to Zoe and Andrew for review.

**Comment by tommygod3** [comment]
Processes have been renamed and awaiting feedback.

**Comment by tommygod3** [comment]
Feedback received, have now changed the names again. Marking completed awaiting PR from my fork.

**Comment by tommygod3** [comment]
Closed by #14
