### ISSUE TITLE
Unify spatial bounds inputs

### ISSUE THREAD

**Issue by agstephens** [cedadev/fawkes-phoenix#12]
Proc 1 currently uses 4 inputs for spatial bounds.
Proc 3 currently uses 2 inputs.

Please unify these so that the input parameter names, titles etc are identical for both processes.

Use 4 separate inputs as used for Proc 1.

Also, on Proc 1 bounds inputs, for the Abstract, include as:
"<name of input>. Note that reducing the size of the bounds will speed up the run-time of the process."

**Comment by tommygod3** [comment]
This has been fixed awaiting merge request from my local fork.

**Comment by tommygod3** [comment]
Closed by #14
