### ISSUE TITLE
Before we go live: rename "hawfinch" to "swallow"?

### ISSUE THREAD

**Issue by agstephens** [cedadev/fawkes-phoenix#5]
Before we go live: I'd like to rename "hawfinch" to "swallow". Is that a lot of work? 

Note that you can rename a github repo under "Settings".

**Comment by tommygod3** [comment]
This has been done for both the [cedadev](https://github.com/cedadev/swallow) version and my own [fork](https://github.com/tommygod3/swallow), as well as the playbook on Gitlab.
