### ISSUE TITLE
Write a nice test suite for the namewps 

### ISSUE THREAD

**Issue by agstephens** [cedadev/fawkes-phoenix#6]
In the test module(s)/package(s) in `namewps`, create a suite of tests that span a reasonable set of different inputs available to each WPS process:

 - maybe randomly select locations/times etc in the test suite but _record_ any successes and failures so we can diagnose them.

 - collect up a set of _good_ inputs so that we can provide users with _canned_ examples.

**Comment by tommygod3** [comment]
Done, see this [PR](https://github.com/cedadev/swallow/pull/3) on swallow.
