### ISSUE TITLE
Add some images to processes

### ISSUE THREAD

**Issue by agstephens** [cedadev/fawkes-phoenix#7]
On this page you get a list of processes and there is a space for an image for each:

https://name-staging.ceda.ac.uk/processes/list?wps=hawfinch

I suggest that you use the main NAME banner with some extra text (black on white) underneath that says the name of the process. The banner is here:

https://name-staging.ceda.ac.uk/static/phoenix/img/NAME_banner_trans.png

Adding some text under it would expand it into the rectangle expected in the processes page. 

(Don't spend long on this - if annoying, just use the banner as is for all of them).

**Comment by tommygod3** [comment]
This has been fixed awaiting merge request from my local fork.
This required metadata to be added to the processes including a link to the process' "picture".
See here:
https://github.com/tommygod3/swallow/blob/29bf2a6049d2d254e21b5708ab66a63f4bafec45/swallow/processes/wps_name_standard.py#L83
